递归函数是在一个函数中通过名字调用自身的情况下构成的，如下：
```javascript
function factorial(num) {
  if(num<=1){
    return 1;
  }else{
    return num*factorial(num-1)
  }
}
```
这是一个经典的结成函数。虽然这个函数表面看起来没有什么问题，但是下面的代码可能导致他出错。
```javascript
var anotherFactorial = factorial;
factorial = null;
console.log(anotherFactorial(4));//出错
```
```javascript
/*
* 【递归函数】:一个函数通过名字调用自身。
* */
function factorial(num) {
    if (num <= 1) {
        return 1//函数的返回值，函数值行并不会输出
    } else {
        return num * factorial(num - 1)
    }
}
console.log(factorial(5));//5*4*3*2

let anotherFactorial = factorial;
factorial=null;
console.log(anotherFactorial(4));

//////////////

//2、arguments.callee的用法，callee是是一个正在指向正在执行的函数的指针，他指向arguments这个对象所属的函数。
function factorial2(num) {
    if (num <= 1) {
        return 1//函数的返回值，函数值行并不会输出
    } else {
        return num * arguments.callee(num - 1)
    }
}
console.log(factorial2(5));//5*4*3*2
let anotherFactorial2 = factorial2;
factorial2=null;
console.log(anotherFactorial2);
console.log(factorial2);
console.log(anotherFactorial2);
console.log(anotherFactorial2(4));//24

///////////////////////

//3、但是在严格模式下，不能通过脚本访问arguments.callee，，访问这个属性会出错。不过可以使用命名函数表达式来达到相同的效果。
let factorial3 = (function f(num) {
    if(num<=1){
        return 1
    }else{
        return num*f(num-1);
    }
});//最外面那个小括号可有可无
console.log(factorial3(5));//120
//以上代码创建了一个命名函数表达式，然后将它赋值给变量factorial3,即使给函数赋值给另外一个变量，函数的名字f仍然有效，所以递归调用可以继续完成。

```
